// src/lib/topicSlugs.js
export const TOPIC_SLUGS = {
    "Array": "array",
    "String": "string",
    "Hash Table": "hash-table",
    "Dynamic Programming": "dynamic-programming",
    "Math": "math",
    "Sorting": "sorting",
    "Greedy": "greedy",
    "Depth-First Search": "depth-first-search",
    "Binary Search": "binary-search",
    "Database": "database",
    "Matrix": "matrix",
    "Tree": "tree",
    "Breadth-First Search": "breadth-first-search",
    "Bit Manipulation": "bit-manipulation",
    "Two Pointers": "two-pointers",
    "Prefix Sum": "prefix-sum",
    "Heap (Priority Queue)": "heap-priority-queue",
    "Simulation": "simulation",
    "Binary Tree": "binary-tree",
    "Graph": "graph",
    "Stack": "stack",
    "Counting": "counting",
    "Sliding Window": "sliding-window",
    "Design": "design",
    "Enumeration": "enumeration",
    "Backtracking": "backtracking",
    "Union Find": "union-find",
    "Linked List": "linked-list",
    "Number Theory": "number-theory",
    "Ordered Set": "ordered-set",
    "Monotonic Stack": "monotonic-stack",
    "Segment Tree": "segment-tree",
    "Trie": "trie",
    "Combinatorics": "combinatorics",
    "Bitmask": "bitmask",
    "Divide and Conquer": "divide-and-conquer",
    "Queue": "queue",
    "Recursion": "recursion",
    "Geometry": "geometry",
    "Binary Indexed Tree": "binary-indexed-tree",
    "Memoization": "memoization",
    "Hash Function": "hash-function",
    "Binary Search Tree": "binary-search-tree",
    "Shortest Path": "shortest-path",
    "String Matching": "string-matching",
    "Topological Sort": "topological-sort",
    "Rolling Hash": "rolling-hash",
    "Game Theory": "game-theory",
    "Interactive": "interactive",
    "Data Stream": "data-stream",
    "Monotonic Queue": "monotonic-queue",
    "Brainteaser": "brainteaser",
    "Doubly-Linked List": "doubly-linked-list",
    "Randomized": "randomized",
    "Merge Sort": "merge-sort",
    "Counting Sort": "counting-sort",
    "Iterator": "iterator",
    "Concurrency": "concurrency",
    "Probability and Statistics": "probability-and-statistics",
    "Quickselect": "quickselect",
    "Suffix Array": "suffix-array",
    "Line Sweep": "line-sweep",
    "Minimum Spanning Tree": "minimum-spanning-tree",
    "Bucket Sort": "bucket-sort",
    "Shell": "shell",
    "Reservoir Sampling": "reservoir-sampling",
    "Strongly Connected Component": "strongly-connected-component",
    "Eulerian Circuit": "eulerian-circuit",
    "Radix Sort": "radix-sort",
    "Rejection Sampling": "rejection-sampling",
    "Biconnected Component": "biconnected-component"
  };
  